# Generated by Django 3.1.1 on 2020-12-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prima_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articolo',
        ),
        migrations.DeleteModel(
            name='Giornalista',
        ),
    ]
