# Generated by Django 3.1.1 on 2020-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autore_ms',
            options={'verbose_name': 'Autore', 'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='genere_ms',
            options={'verbose_name': 'Genere', 'verbose_name_plural': 'Generi'},
        ),
        migrations.AlterModelOptions(
            name='libro_ms',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libri'},
        ),
        migrations.AlterField(
            model_name='libro_ms',
            name='titolo',
            field=models.CharField(max_length=100),
        ),
    ]
